package com.citrix;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Order Line Item")
public class OrderLineItem implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Order ID")
	private java.lang.String order_ID;
	@org.kie.api.definition.type.Label(value = "OrderLine ID")
	private java.lang.String orderLine_ID;
	@org.kie.api.definition.type.Label(value = "Product Type")
	private java.lang.String product_Type;
	@org.kie.api.definition.type.Label(value = "Edition")
	private java.lang.String edition;
	@org.kie.api.definition.type.Label(value = "SKU Marketing")
	private java.lang.String SKU_Marketing;
	@org.kie.api.definition.type.Label(value = "Product Line ID")
	private java.lang.String product_Line_ID;
	@org.kie.api.definition.type.Label(value = "Discount Program")
	private java.lang.Double discount_Program;
	@org.kie.api.definition.type.Label(value = "Discount Channel")
	private java.lang.Double discount_Channel;
	@org.kie.api.definition.type.Label(value = "Discount Program Amount")
	private java.lang.Double discount_Program_Amount;
	@org.kie.api.definition.type.Label(value = "SRP USD")
	private java.lang.Double SRP_USD;

	public OrderLineItem() {
	}

	public java.lang.String getOrder_ID() {
		return this.order_ID;
	}

	public void setOrder_ID(java.lang.String order_ID) {
		this.order_ID = order_ID;
	}

	public java.lang.String getOrderLine_ID() {
		return this.orderLine_ID;
	}

	public void setOrderLine_ID(java.lang.String orderLine_ID) {
		this.orderLine_ID = orderLine_ID;
	}

	public java.lang.String getProduct_Type() {
		return this.product_Type;
	}

	public void setProduct_Type(java.lang.String product_Type) {
		this.product_Type = product_Type;
	}

	public java.lang.String getEdition() {
		return this.edition;
	}

	public void setEdition(java.lang.String edition) {
		this.edition = edition;
	}

	public java.lang.String getSKU_Marketing() {
		return this.SKU_Marketing;
	}

	public void setSKU_Marketing(java.lang.String SKU_Marketing) {
		this.SKU_Marketing = SKU_Marketing;
	}

	public java.lang.String getProduct_Line_ID() {
		return this.product_Line_ID;
	}

	public void setProduct_Line_ID(java.lang.String product_Line_ID) {
		this.product_Line_ID = product_Line_ID;
	}

	public java.lang.Double getDiscount_Program() {
		return this.discount_Program;
	}

	public void setDiscount_Program(java.lang.Double discount_Program) {
		this.discount_Program = discount_Program;
	}

	public java.lang.Double getDiscount_Channel() {
		return this.discount_Channel;
	}

	public void setDiscount_Channel(java.lang.Double discount_Channel) {
		this.discount_Channel = discount_Channel;
	}

	public java.lang.Double getDiscount_Program_Amount() {
		return this.discount_Program_Amount;
	}

	public void setDiscount_Program_Amount(
			java.lang.Double discount_Program_Amount) {
		this.discount_Program_Amount = discount_Program_Amount;
	}

	public java.lang.Double getSRP_USD() {
		return this.SRP_USD;
	}

	public void setSRP_USD(java.lang.Double SRP_USD) {
		this.SRP_USD = SRP_USD;
	}

	public OrderLineItem(java.lang.String order_ID,
			java.lang.String orderLine_ID, java.lang.String product_Type,
			java.lang.String edition, java.lang.String SKU_Marketing,
			java.lang.String product_Line_ID,
			java.lang.Double discount_Program,
			java.lang.Double discount_Channel,
			java.lang.Double discount_Program_Amount, java.lang.Double SRP_USD) {
		this.order_ID = order_ID;
		this.orderLine_ID = orderLine_ID;
		this.product_Type = product_Type;
		this.edition = edition;
		this.SKU_Marketing = SKU_Marketing;
		this.product_Line_ID = product_Line_ID;
		this.discount_Program = discount_Program;
		this.discount_Channel = discount_Channel;
		this.discount_Program_Amount = discount_Program_Amount;
		this.SRP_USD = SRP_USD;
	}

}