package com.citrix;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderHeader implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OrderHeader() {
    }




}