package com.citrix;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PartnerFunctions implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PartnerFunctions() {
    }




}