package com.citrix;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PartnerInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Tags")
	private Tag tags;

	public PartnerInfo() {
	}

	public com.citrix.Tag getTags() {
		return this.tags;
	}

	public void setTags(com.citrix.Tag tags) {
		this.tags = tags;
	}

	public PartnerInfo(com.citrix.Tag tags) {
		this.tags = tags;
	}

}