package com.citrix;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RewardRegistration implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Registration_ID")
	private java.lang.String registration_ID;
	@org.kie.api.definition.type.Label(value = "Incentive Type")
	private java.lang.String incentive_Type;
	@org.kie.api.definition.type.Label(value = "Reward Submitted Date")
	private java.time.LocalDate reward_Submitted_Date;
	@org.kie.api.definition.type.Label(value = "Backend Applicable Flag")
	private java.lang.Boolean backendApplicable_Flag;
	@org.kie.api.definition.type.Label(value = "Frontend Applicable Flag")
	private java.lang.Boolean frontendApplicable_Flag;
	@org.kie.api.definition.type.Label(value = "Initial Submitted Date")
	private java.time.LocalDate initial_Submitted_Date;

	public RewardRegistration() {
	}

	public java.lang.String getRegistration_ID() {
		return this.registration_ID;
	}

	public void setRegistration_ID(java.lang.String registration_ID) {
		this.registration_ID = registration_ID;
	}

	public java.lang.String getIncentive_Type() {
		return this.incentive_Type;
	}

	public void setIncentive_Type(java.lang.String incentive_Type) {
		this.incentive_Type = incentive_Type;
	}

	public java.time.LocalDate getReward_Submitted_Date() {
		return this.reward_Submitted_Date;
	}

	public void setReward_Submitted_Date(
			java.time.LocalDate reward_Submitted_Date) {
		this.reward_Submitted_Date = reward_Submitted_Date;
	}

	public java.lang.Boolean getBackendApplicable_Flag() {
		return this.backendApplicable_Flag;
	}

	public void setBackendApplicable_Flag(
			java.lang.Boolean backendApplicable_Flag) {
		this.backendApplicable_Flag = backendApplicable_Flag;
	}

	public java.lang.Boolean getFrontendApplicable_Flag() {
		return this.frontendApplicable_Flag;
	}

	public void setFrontendApplicable_Flag(
			java.lang.Boolean frontendApplicable_Flag) {
		this.frontendApplicable_Flag = frontendApplicable_Flag;
	}

	public java.time.LocalDate getInitial_Submitted_Date() {
		return this.initial_Submitted_Date;
	}

	public void setInitial_Submitted_Date(
			java.time.LocalDate initial_Submitted_Date) {
		this.initial_Submitted_Date = initial_Submitted_Date;
	}

	public RewardRegistration(java.lang.String registration_ID,
			java.lang.String incentive_Type,
			java.time.LocalDate reward_Submitted_Date,
			java.lang.Boolean backendApplicable_Flag,
			java.lang.Boolean frontendApplicable_Flag,
			java.time.LocalDate initial_Submitted_Date) {
		this.registration_ID = registration_ID;
		this.incentive_Type = incentive_Type;
		this.reward_Submitted_Date = reward_Submitted_Date;
		this.backendApplicable_Flag = backendApplicable_Flag;
		this.frontendApplicable_Flag = frontendApplicable_Flag;
		this.initial_Submitted_Date = initial_Submitted_Date;
	}

}