package com.citrix;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Tag")
public class Tag implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Tag ID")
	private java.lang.String tagID;
	@org.kie.api.definition.type.Label("Tag Name")
	private java.lang.String tagName;

	public Tag() {
	}

	public java.lang.String gettagID() {
		return this.tagID;
	}

	public void settagID(java.lang.String tagID) {
		this.tagID = tagID;
	}

	public java.lang.String gettagName() {
		return this.tagName;
	}

	public void settagName(java.lang.String tagName) {
		this.tagName = tagName;
	}

	public Tag(java.lang.String tagID, java.lang.String tagName) {
		this.tagID = tagID;
		this.tagName = tagName;
	}

}