package com.citrix;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Tag")
public class Tag implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Tag ID")
	private java.lang.String TagID;
	@org.kie.api.definition.type.Label("Tag Name")
	private java.lang.String TagName;

	public Tag() {
	}

	public java.lang.String getTagID() {
		return this.TagID;
	}

	public void setTagID(java.lang.String TagID) {
		this.TagID = TagID;
	}

	public java.lang.String getTagName() {
		return this.TagName;
	}

	public void setTagName(java.lang.String TagName) {
		this.TagName = TagName;
	}

	public Tag(java.lang.String TagID, java.lang.String TagName) {
		this.TagID = TagID;
		this.TagName = TagName;
	}

}