package com.citrix;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Tags implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Tags() {
    }




}